// Code generated by MockGen. DO NOT EDIT.
// Source: with_tool_directive.go
//
// Generated by this command:
//
//	mockgen -source=with_tool_directive.go -destination=mock_with_tool_directive.go -package=withtooldirective
//

// Package withtooldirective is a generated GoMock package.
package withtooldirective
